# Generated by Django 3.2.8 on 2021-10-31 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='restaurant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
    ]
