# Generated by Django 3.2.8 on 2021-10-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_schedule_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default=None, upload_to='restaurants_logo'),
        ),
    ]
